--- #YAML:1.0
name:               MooseX-App-Cmd
version:            0.06
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    App::Cmd:             0.3
    Getopt::Long::Descriptive:  0
    Moose:                0.86
    MooseX::Getopt:       0.18
    Test::use::ok:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
